### ISSUE TITLE
Disable "oof"/slow motion?

### ISSUE THREAD

**Issue by Vuiz** [Metapyziks/csgo-retakes-ziksallocator#21]
Is there a way to disable the slow motion effect? We love the plugin but find this feature too much, I tried removing the oof.sp file but the effect still occurs. Thanks for the great plugin otherwise!

**Comment by Metapyziks** [comment]
Hey @Vuiz, I hadn't really thought that other servers would be running this. In the short term I'll make sure everything can be disabled with convars, and will hopefully split it up into separate optional plugins eventually.

**Comment by Metapyziks** [comment]
Added `sm_oof_enabled`, which is `0` by default.
