### ISSUE TITLE
[IDEA] [REQ] Translate

### ISSUE THREAD

**Issue by wasyady** [Metapyziks/csgo-retakes-ziksallocator#4]
Is there a possibility to add language files?
I can give you German, Romanian and Hungarian translations. :bowtie:

**Comment by Metapyziks** [comment]
Absolutely, I can look into doing that later today. To be honest I wasn't expecting anyone else to use this plugin!

**Comment by wasyady** [comment]
I see you still do it.
Thanks in advance!


Not only that I use it very much like it!
Hungarian retake servers are the first with it my server!

**Comment by Metapyziks** [comment]
Should be done now, please let me know if there are any missing phrases I should add:

https://github.com/Metapyziks/csgo-retakes-ziksallocator/blob/master/translations/ziksallocator.phrases.txt

Also, thank you for offering to provide translations!
